name: OwnCloud Product
description: Access & share your files, calendars, contacts, mail & more from any device, on your terms
shortDescription: OwnCloud is your own personal cloud
imagePath: https://owncloud.org/wp-content/themes/owncloudorgnew/assets/img/common/logo_owncloud.svg
version: 0.0.1
updateDate: June 29, 2016
public: false

# Allow for single panel fact collection.
fields:

  # Data Center field.
  - name: datacenter
    displayName: Datacenter Picker
    type: datacenters
    required: true

  # Sample password field
  - name: mysqlpass
    displayName: MySQL Password
    type: password
    required: true

tags:
  - cloud
