---
- name: Install and configure MySQL
  hosts: all
  gather_facts: True
  roles:
    - role: mysql
      tags:
        - db

- name: Get additional packages
  hosts: all
  gather_facts: True
  roles:
    - role: packages
      tags:
        - pkg

- name: Install Owncloud
  hosts: all
  gather_facts: False
  roles:
    - role: owncloud
      tags:
        - owncloud

- name: Copy mysql.ini and owncloud.conf files over
  hosts: all
  gather_facts: False
  roles:
    - role: file_xfer
      tags:
        - config

- name: Configure apache and postfix
  hosts: all
  gather_facts: False
  roles:
    - role: apache_postfix
      tags:
        - appost
