---
- name: Create infrastructure
  hosts: all
  gather_facts: False
  connection: local
  roles:
    - { role: infra, tags:['clc']}

- name: Install Owncloud
  hosts: oc_servers
  gather_facts: False
  roles:
    - { role: owncloud, tags:['always'] }
