---
- name: Copy mysql.ini and owncloud.conf files over
  hosts: all
  gather_facts: False
  roles:
    - role: file_xfer
      tags:
        - config

- name: Configure apache and postfix
  hosts: all
  gather_facts: False
  roles:
    - role: apache_postfix
      tags:
        - appost
