- name: Install list of packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - ibapache2-mod-php5
    - php5-gd
    - php5-json
    - php5-mysql
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-imagick
    - php5-apcu/trusty-backports
  tags:
    - pkg
