---
- name: Install list of packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - apache2
    - libapache2-mod-php5
    - php5-gd
    - php5-json
    - php5-mysql
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-imagick
    - php5-apcu/trusty-backports
  tags:
    - always
