---
- name: Copy file to /etc/apt/preferences to enable Trusty Backports
  copy: src=files/preferences dest=/etc/apt/preferences
  tags:
    - always

- name: First list of packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - apache2
    - libapache2-mod-php5
  tags:
    - always

- name: Second list of packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - php5-gd
    - php5-json
    - php5-mysql
    - php5-curl
  tags:
    - always

- name: Third list of packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - php5-intl
    - php5-mcrypt
    - php5-imagick
  tags:
    - always

- name: Run manual install of php5-apcu/trusty-backports
  shell: apt-get install -y php5-apcu/trusty-backports
  tags:
    - always

- name: Equivilent of apt-get upgrade
  apt: upgrade=dist
  tags:
    - always
