---
- name: Modify apache config
  blockinfile:
    dest: /etc/apache2/apache2.conf
    insertbefore: #<Directory /srv/>
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
           <Directory /data/www/owncloud>
             Options Indexes FollowSymLinks
             AllowOverride None
             Require all granted
           </Directory>

  tags:
    - appost

- name: Install apache modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
    - ssl
  tags:
    - appost

- name: Enable apache site
  shell: a2ensite default-ssl
  tags:
    - appost

- name: Modify default-ssl.conf
  blockinfile:
    dest: /etc/apache2/sites-available/default-ssl.conf
    insertbefore: </VirtualHost>
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
          <Directory /data/www/owncloud>
            Options Indexes FollowSymLinks
            AllowOverride All
            Order allow,deny
            allow from all
          </Directory>

  tags:
    - appost
  notify: Restart Apache

- name: Configure postfix
  lineinfile: dest=/etc/postfix/main.cf state=present line='relayhost = relay.t3mx.com'
  tags:
    - appost

- name: Copy example config.php to server
  copy: src=files/example_config.php dest={{ ocpath }}/example_config.php
  tags:
    - appost
