---
- name: Modify apache config
  blockinfile:
    dest: /etc/apache2/apache2.conf
    insertbefore: ^#<Directory /srv/>
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
<<<<<<< HEAD
           <Directory {{ permpath }}>
             Options Indexes FollowSymLinks
             AllowOverride None
             Require all granted
           </Directory>
=======
      <Directory /data/www/owncloud>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
      </Directory>
>>>>>>> 35246de4533702a294baa631448d6f5754ffb489

- name: Remove the default www settings
  blockinfile:
    dest: /etc/apache2/apache2.conf
    state: absent
    content: |
      <Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
      </Directory>

- name: Install apache modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
    - ssl

- name: Enable apache site
  shell: a2ensite default-ssl

- name: Modify default-ssl.conf
  blockinfile:
    dest: /etc/apache2/sites-available/default-ssl.conf
    insertbefore: </VirtualHost>
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
<<<<<<< HEAD
          <Directory {{ permpath }}>
=======
          <Directory /data/www/owncloud>
>>>>>>> 35246de4533702a294baa631448d6f5754ffb489
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
          </Directory>
  notify: Restart Apache

- name: Configure postfix
  lineinfile: dest=/etc/postfix/main.cf state=present line='relayhost = relay.t3mx.com'

- name: Copy example config.php to server
  copy: src=files/example_config.php dest={{ ocpath }}/example_config.php

- name: set permissions on www dir
<<<<<<< HEAD
  shell: chmod -R 755 {{ permpath }}
=======
  shell: chmod -R 755 /data/www/owncloud
>>>>>>> 35246de4533702a294baa631448d6f5754ffb489
