---
- name: Create directories
  file: path={{ ocroot }}/www state=directory

- name: Download owncloud tarball
  get_url: url=https://download.owncloud.org/community/owncloud-9.0.2.tar.bz2 dest={{ ocroot }}/owncloud-9.0.2.tar.bz2 validate_certs=no checksum=md5:a0131f5cae2b1503b8de6796487c1bdc

- name: unzip the bzip
  command: tar xvfj {{ ocroot }}/owncloud-9.0.2.tar.bz2

- name: Copy data to wwwroot
  shell: cp -r owncloud {{ ocroot }}/www/
