---
- name: Create directories
  file: path=data_oc/www state=directory

- name: Download owncloud tarball
  get_url: url=https://download.owncloud.org/community/owncloud-9.0.2.tar.bz2 dest=/data_oc/owncloud-9.0.2.tar.bz2 validate_certs=no checksum=md5:a0131f5cae2b1503b8de6796487c1bdc

- name: Run only if it hasn't been done already
  stat: path=/data_oc/www/owncloud
  register: st

- name: Extract the Tarball
  shell: tar -xjf owncloud-9.0.2.tar.bz2
  args:
    chdir: "/data_oc"
  when: not st.stat.exists

- name: Copy data to wwwroot
  shell: cp -r /data_oc/owncloud /data_oc/www/
  when: not st.stat.exists
